//Tile Settings
#define NUMBEROFTILESX 28
#define NUMBEROFTILESY 31
#define PIXELPERTILE 16

//Pacman Settings
#define PACMAN_SPEED 5

//Ghost setting
#define GHOST_SPEED 3
#define GHOST_DEAD_DURATION 3000
//Assets Settings
#define PACMAN_ASSETS_NUM 3

#define GHOST_ASSETS_RESERVE 17
#define GHOST_ASSETS_NUM 8
#define GHOST_SCARED_ASSETS_NUM 5
#define GHOST_EYE_ASSETS_NUM 4
#define LARGE_FOOD_NUM 4
#define SMALL_FOOD_NUM 240

//Score
#define SCORE_FOOD 10

//Other
#define PILL_DURATION 10000
#define DONT_FLASH_DURATION 7000
#define PI 3.14159265358979323846
